name: Pre-release

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/pre-release.yml

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Build pwebm-helper.js
        run: bun run build

      - name: Delete previous pre-release if it exists
        run: |
          if gh release view bleeding-edge &>/dev/null; then
            gh release delete --yes --cleanup-tag bleeding-edge
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new pre-release
        run: |
          gh release create bleeding-edge dist/pwebm-helper.js \
            --title "bleeding-edge" \
            --notes "Pre-release with the latest commits" \
            --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
